accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns= [
    path('user/', views.UserCreateView.as_view(), name='user'),

]

djangosettings/urls.py
from django.contrib import admin
from django.urls import path,include
from settingsdemo.views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(),name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('accounts/', include('accounts.urls')),


]

accounts/models.py
from django.utils.timezone import now
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from accounts.constant import gender_choices
from django.core.validators import MaxLengthValidator,MinLengthValidator

class User(AbstractUser):
    image = models.ImageField(upload_to='images/profile_image/', default='user-default.png')
    phone_number = models.CharField(null=True,max_length=13,validators=[MaxLengthValidator(13),MinLengthValidator(10)])
    gender = models.CharField(choices=gender_choices, null=True, max_length=10)
    birthday = models.DateField(null=True)

    class Meta:
        ordering = ['username', ]

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('home')

settingsdemo/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from .models import User
from django.contrib.auth import authenticate,login
# Create your views here.
class UserCreateView(CreateView):
    model = User
    fields = ['username','password', 'phone_number', 'gender', 'birthday', 'image']
    def form_valid(self, form):
        user = super().form_valid(form)
        self.object.set_password(form.cleaned_data['password'])
        self.object.save()
        login(self.request, self.object)
        return user
        

settingsdemo/views.py
from django.shortcuts import render,HttpResponse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(LoginRequiredMixin,View):
    def get(self,request):
        user = {'name':request.user}
        print(request.user,request.user.id)
        return render(request,'settingsdemo/index.html',context={'user':request.user})

settingsdemo/templates/settingsdemo/index.html
<html>
    
    <body>
        <a href="logout/">logout</a>
        In app
    </body>
</html>

templates/accounts/user_form.html
{% load static %}
<!DOCTYPE HTML5>
<html>

<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->

    <style>
        .border-bottom {
            border-color: #eee;
        }
    </style>
</head>

<body style="background-color: #e3e7e5;">
    <div class="container">
        <div class="row">
            <div class="main col-md-10">
                <div class="row">
                    <div class="col-md-6 text-center offset-3">
                        <div class="pb-2 mt-4 mb-2 border-bottom">
                            <h1>User Form</h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-md-6 form-area offset-3">
                        <form role="form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" value="{% if form.username.value%} {{form.username.value}} {%endif%}"
                                    class="form-control" id="id_username" name="username" placeholder="Name" required>
                            </div>
                            {%for error in form.username.errors%}
                            <div class="alert alert-danger">
                                <strong>{{ error }}</strong>
                            </div>
                            {%endfor%}
                            <div class="form-group">
                                <input type="text"
                                    value="{% if form.phone_number.value%} {{form.phone_number.value}} {%endif%}"
                                    class="form-control" id="id_phone_number" name="phone_number"
                                    placeholder="Mobile Number" required>
                            </div>
                            {%for error in form.phone_number.errors%}
                            <div class="alert alert-danger">
                                <strong>{{ error }}</strong>
                            </div>
                            {%endfor%}
                            <div class="form-group">
                                {{ form.gender }}
                            </div>
                            {%for error in form.gender.errors%}
                            <div class="alert alert-danger">
                                <strong>{{ error }}</strong>
                            </div>
                            {%endfor%}
                            <div class="form-group">
                                <input type="text" class="form-control" id="id_birthday" name="birthday"
                                    placeholder="Date of Birth(YYYY-MM-DD)" required>
                            </div>
                            {%for error in form.birthday.errors%}
                            <div class="alert alert-danger">
                                <strong>{{ error }}</strong>
                            </div>
                            {%endfor%}
                            <div class="form-group">
                                    <input type="text" class="form-control" id="id_password" name="password" placeholder="Password" required>
                                </div>
                                {%for error in form.password.errors%}
                                <div class="alert alert-danger">
                                    <strong>{{ error }}</strong>
                                </div>
                                {%endfor%}
                                
                            <div class="form-group">
                                <label class=" btn btn-primary btn-file">
                                    Upload Profile Photo<input class="form-control-file custom-file-input d-none"
                                        style="display: none;" type="file" name="image" accept="image/*" id="id_image"/>
                                </label>
                                <label id="filename">Choose image</label>
                            </div>
                            <input class="btn btn-primary" type="submit" style="background-color: #3f00ff;
                    color: #fff;
                    font-size: 14px;
                    padding: 5px 20px;
                    border: none;" value="Save">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('#id_image').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $('#filename').html(fileName.split("\\").pop());
            })
        $(".side-menu-anchor").removeClass("active")
        $('#add-user-anchor').addClass("active")
    </script>
</body>

</html>

templates/settingsdemo/index.html
<html>
    {{ user.username }}</br>
    Out side app</br>
    <a href="logout/">logout</a>

    
</html>